name: Deploy
on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
     name: Tests
     runs-on: [self-hosted, small]
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/workflows/actions/prepare
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           registry: hyperskill.azurecr.io
           username: ${{ secrets.REGISTRY_USER }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
       - run: docker pull hyperskill.azurecr.io/epicbox/python:3.10.6-011c5b05a
       - run: poetry run pytest .
